### ISSUE TITLE
Playing a tournament with a policy that assigns a probability of 0 to some action causes errors 

### ISSUE THREAD

**Issue by grubbling-gilles** [probberechts/ML_project20#1]
When playing a tournament we get the following error 

```
Traceback (most recent call last):
  File "/home/gilles/git-repos/ml-project/kuhn_poker/play_tournament.py", line 20, in <module>
    ranking, results = play_tournament(game, modeldir, rounds)
  File "/home/gilles/git-repos/ml-project/ML_project20/tournament.py", line 131, in play_tournament
    os.path.join(modeldir, f"{team2}_p2.csv"))
  File "/home/gilles/git-repos/ml-project/ML_project20/tournament.py", line 105, in play_match
    action = sample_action(state, state.current_player())
  File "/home/gilles/git-repos/ml-project/ML_project20/tournament.py", line 71, in sample_action
    raise e
  File "/home/gilles/git-repos/ml-project/ML_project20/tournament.py", line 67, in sample_action
    probs[action] = policy_probs[action]
KeyError: 0
```

This error is caused in the following piece of code 

```
def sample_action(state, player_id):
        cur_legal_actions = state.legal_actions(player_id)
        # Remove illegal actions, re-normalize probs
        probs = np.zeros(num_actions)
        policy_probs = agents[player_id].action_probabilities(state, player_id=player_id)
        for action in cur_legal_actions:
            probs[action] = policy_probs[action]
        probs /= sum(probs)
        action = np.random.choice(len(probs), p=probs)
        return action
```

The function `TabularPolicy.action_probabilities(state, player_id) only returns probabilities for actions with probabilities larger than 0. This causes a key error in the for loop when there are actions where the probability is actually 0. 

For now I have fixed this issue by changing the for loop to 

```
for action in cur_legal_actions:
            try:
                probs[action] = policy_probs[action]
            except KeyError:
                probs[action] = 0
```

**Comment by elkhrt** [comment]
Sorry, this is a little tricky. `Policy` objects don't always return probabilities for every legal action.

However, there are cleaner ways to do what you want to do. If you were sure you had a valid policy (with no need to mask out illegal actions or renormalize) you could just do:
```
def sample_action(state, player_id):
  policy_probs = agents[player_id].action_probabilities(state, player_id=player_id)
  return np.random.choice(list(policy_probs.keys()), p=list(policy_probs.values()))
```
I would **strongly** recommend you don't pass invalid policies around, but instead mask and renormalize as you create / update them. For a `TabularPolicy` object, you can do this as follows:
```
# `p` is an array of size [num_state, num_actions], potentially with non-zero values on illegal actions or not summing to 1 
p *= policy_nn.legal_actions_mask
p /= p.sum(axis=-1, keepdims=True)
tabular_policy.action_probability_array = p
```

**Comment by elkhrt** [comment]
You're not the first person to have run into this, so we will be changing `TabularPolicy` to always return an entry for all legal actions in the next update (on Monday), which should make this a bit less tricky for users Thanks for reporting the problem!
